### ISSUE TITLE
luarocks installation of 5.1.0 fails

### ISSUE THREAD

**Issue by jeichorn** [Kong/lua-resty-dns-client#100]
```
Error: Build error: Failed installing src/resty/dns/utils.lua in /usr/local/openresty/luajit/lib/luarocks/rocks-5.1/lua-resty-dns-client/5.1.0-1/lua/resty/dns/utils.lua: The source and destination are the same files
```

**Comment by locao** [comment]
Thanks for the notice, @jeichorn. It should be fixed now, maybe you will need to delete the cache for the rock before trying to install it again. It depends where the cache is in your system but should be something like:
```rm ~/.cache/luarocks/https___luarocks.org/lua-resty-dns-client-5.1.0-1*```

I'm closing this now, please feel free to reopen if the problem still occurs for you.
