### ISSUE TITLE
luarocks package 5.1.1 installs penlight 1.0.0-1 which does not work in Openresty (it nukes the whole Global context)

### ISSUE THREAD

**Issue by Unigoge** [Kong/lua-resty-dns-client#101]
I think it was caused by changing "penlight > 1.1, < 2.0" to "penlight ~> 1.0" in rockspec file

to reproduce:

- add `local pretty = require "pl.pretty"` anywhere in the source code - after that `getfenv(0)` starts to return an empty table.

**Comment by Tieske** [comment]
thx! fixed in https://github.com/Kong/lua-resty-dns-client/commit/63752d7128eee1e47708fb366d3cfe31887566c9

rock uploaded.
