### ISSUE TITLE
Roundrobin fails for records with zero weight.

### ISSUE THREAD

**Issue by quark-tekliner** [Kong/lua-resty-dns-client#21]
When dns server returns SRV record like
_cool_service._tcp.cluster.local. 60 IN SRV 0 0 12345 cool_service.cluster.local.
In this https://github.com/Mashape/lua-resty-dns-client/blob/master/src/resty/dns/client.lua#L1173 loop `weightList[i]` will be 0, so `rrwList` will be empty after loop. I gues it may be fixed by `for _ = 0, weightList[i] do`.

**Comment by Tieske** [comment]
Reopening this because the same issue will be present in the balancer, and needs fixing.

@quark-tekliner thx for the report!

**Comment by Tieske** [comment]
ref, see `weight` at the bottom of page 2: https://www.ietf.org/rfc/rfc2782.txt
