### ISSUE TITLE
srv record with skydns error

### ISSUE THREAD

**Issue by mfcliu** [Kong/lua-resty-dns-client#36]
I tried with skydns server :

[root@kong2 dns]# dig @localhost SRV demo.dev.east.ppdai.local                                                                               

; <<>> DiG 9.9.4-RedHat-9.9.4-37.el7 <<>> @localhost SRV demo.dev.east.ppdai.local
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56605
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 2

;; QUESTION SECTION:
;demo.dev.east.ppdai.local.     IN      SRV

;; ANSWER SECTION:
demo.dev.east.ppdai.local. 3600 IN      SRV     10 50 8080 1.demo.dev.east.ppdai.local.
demo.dev.east.ppdai.local. 3600 IN      SRV     10 50 8090 2.demo.dev.east.ppdai.local.

;; ADDITIONAL SECTION:
1.demo.dev.east.ppdai.local. 3600 IN    A       192.168.8.135
2.demo.dev.east.ppdai.local. 3600 IN    A       192.168.8.136

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Feb 07 20:37:13 CST 2018
;; MSG SIZE  rcvd: 173

[root@kong2 dns]# dig @localhost SRV 1.demo.dev.east.ppdai.local

; <<>> DiG 9.9.4-RedHat-9.9.4-37.el7 <<>> @localhost SRV 1.demo.dev.east.ppdai.local
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57838
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;1.demo.dev.east.ppdai.local.   IN      SRV

;; ANSWER SECTION:
1.demo.dev.east.ppdai.local. 3600 IN    SRV     10 100 8080 1.demo.dev.east.ppdai.local.

;; ADDITIONAL SECTION:
1.demo.dev.east.ppdai.local. 3600 IN    A       192.168.8.135

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Feb 07 20:37:46 CST 2018
;; MSG SIZE  rcvd: 108

cause  "recursion detected" exception。 

I fix it like this :

/dns/client.lua

--print(tostring(try_list))
  if rec[1].type == _M.TYPE_SRV then
    local entry = rec[roundRobinW(rec)]
    -- our SRV entry might still contain a hostname, so recurse, with found port number
    local srvport = (entry.port ~= 0 and entry.port) or port -- discard port if it is 0
    try_status(try_list, "dereferencing SRV")
    local rec1, err1
    local opts = {}
    opts.qtype = _M.TYPE_A
    rec1, err1, try_list = resolve(entry.target, opts, dnsCacheOnly, nil)
    if err1 then
      return nil, err1, try_list
    end
    return rec1[1].address,entry.port,try_list
  else
    -- must be A or AAAA
    return rec[roundRobin(rec)].address, port, try_list
  end
end

works fine。
I do't know wether this exception also occurs with other different type dns servers ?

**Comment by Tieske** [comment]
the recursion happens because the default lookup order is `"last", "SRV", "A", "AAAA", "CNAME" `

When you initialize the client, specify the order `{ "last", "A", "AAAA", "SRV", "CNAME" }`, that should resolve your issue without any code changes.

Can you confirm this?

**Comment by mfcliu** [comment]
I got it works.
I didn't understand the dns order, so  I modified the configuration , change it to SRV only , and that exception occured.
Thanks. I will close this issue.
