### ISSUE TITLE
Link-local IPv6 resolvers fail

### ISSUE THREAD

**Issue by james-callahan** [Kong/lua-resty-dns-client#43]
My resolv.conf:

```
# Generated by NetworkManager
nameserver 192.168.1.254
nameserver 8.8.8.8
nameserver fe80::1%enp0s20f0u1u1
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver fd80::1e5f:2bff:fe92:95c9
```

Results in:

`2018/03/01 15:15:32 [error] 28930#0: *9 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'mockbin.org' with: dns lookup pool exceeded retries (1): failed to create a resolver: failed to set peer name: failed to parse host name "[fe80::1%enp0s20f0u1u1]": invalid IPv6 address, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "example.com"`

Running version 1.0.0-1

**Comment by Tieske** [comment]
The underlying open resty lib doesn't support zone indices, and neither does this library. 

background info: https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses

**Comment by james-callahan** [comment]
> The underlying open resty lib doesn't support zone indices, and neither does this library.

In that case, nameservers with a ipv6 scope should be skipped (rather than causing dns lookups to fail)

**Comment by Tieske** [comment]
Yes that would for now probably be the best option
