### ISSUE TITLE
client resolve always getting ipv6 address

### ISSUE THREAD

**Issue by geemang2000** [Kong/lua-resty-dns-client#45]
DNS running in AD
dc-1.tld.com Type: Host (A) Data: 192.168.0.175
dc-1.tld.com Type: IPv6 Host (AAAA) Data: 2605:....

client.init(  { enable_ipv6 = false, order = { "last", "SRV", "A", "AAAA", "CNAME" } } )
client.resolve("dc-1.tld.com") <- returns [2605..]

Shouldn't the order in the init prefer the A record? Either way, I only want IPv4 records. is this possible?

**Comment by Tieske** [comment]
setting `enable_ipv6 = false` only applies to the name servers used. So in this case it will skip any nameserver addresses in ipv6 format from `resolv.conf`.

That said, based on the order you set `{ "last", "SRV", "A", "AAAA", "CNAME" }` you should first get the `A` result.

If you don't want IPv6 addresses at all then set it to `{ "last", "SRV", "A", "CNAME" }`.

**Comment by Tieske** [comment]
@geemang2000 considering this resolved. Feel free to reopen if you have additional questions.
