### ISSUE TITLE
localhost not treated specially

### ISSUE THREAD

**Issue by james-callahan** [Kong/lua-resty-dns-client#50]
I got `{"message":"name resolution failed"}` from Kong when my upstream had a `localhost` target.

This seems to be because my /etc/hosts is empty. However it should have worked:

From RFC 6761: Section 6.3.3
> Name resolution APIs and libraries SHOULD recognize localhost
> names as special and SHOULD always return the IP loopback address
> for address queries and negative responses for all other query
> types.  Name resolution APIs SHOULD NOT send queries for
> localhost names to their configured caching DNS server(s).

**Comment by Tieske** [comment]
> This seems to be because my /etc/hosts is empty

exactly. Thanks for the report
