### ISSUE TITLE
no require file random.lua in your project

### ISSUE THREAD

**Issue by liulei18** [Kong/lua-resty-dns-client#71]
### Where can i find random.lua file?
* I got a error log
```

2019/07/16 16:48:14 [error] 389667#0: *20 lua entry thread aborted: runtime error: ./lualib/resty/dns/balancer/ring.lua:363: attempt to call field 'new' (a nil value)
stack traceback:
coroutine 0:
	./lualib/resty/dns/balancer/ring.lua: in function 'randomlist'
```
* i read the source code in resty/dns/balancer/ring.lua

```
local lrandom = require "random"
local function randomlist(size)
 xxxx
 ........
  local randomizer = lrandom.new(158841259)
  ........
  xxxx
end
```
* i attemp to find a substitude on github. https://github.com/bungle/lua-resty-random . But not work,because no new() function in the random.lua
* i do not find the random.lua file in your project, can you give me some suggestion? hope for your answer. thanks

**Comment by Tieske** [comment]
It's a LuaRocks dependency, you can use LuaRocks to install it, see https://github.com/Kong/lua-resty-dns-client/blob/master/lua-resty-dns-client-4.0.0-1.rockspec#L20

See https://luarocks.org/modules/edubart/lrandom

**Comment by liulei18** [comment]
As you said, it solved my problem perfectly. Thank you very much again!
