### ISSUE TITLE
Empassioned plea

### ISSUE THREAD

**Issue by onematchfox** [Kong/lua-resty-dns-client#78]
Not an issue as such... But please could I make an empassioned plea to release fix #76. Going through the upgrade process for Kong 1.4.0 I was severely disappointed to find that this fix had not made it in there. I know it's nothing critical, but in a local environment where we have log level set to debug, the verbosity of the logging without this fix drowns out pretty much everything else and makes life more miserable than it needs to be...

**Comment by gszr** [comment]
@onematchfox - Our apologies that the fix didn't make it into 1.4. We've drafted a release PR and will make sure the library version is bumped in Kong as well.

**Comment by Tieske** [comment]
@onematchfox thanks for the nudge, that was indeed an oversight that we missed bumping this. Released minutes ago.

**Comment by onematchfox** [comment]
@gszr @Tieske Thanks so much!
