### ISSUE TITLE
Remove table.move for arm64 compatiblity 

### ISSUE THREAD

**Issue by hbagdi** [Kong/lua-resty-dns-client#93]
https://github.com/Kong/kong/issues/5869

**Comment by Tieske** [comment]
not sure this is the right approach, what are the options to fix LuaJIT @javierguerragiraldez ? wouldn't that be quicker?

**Comment by javierguerragiraldez** [comment]
The fix to LuaJIT (LuaJIT/LuaJIT#583) is simple and looks safe but I'd like some comment from anybody familiar with the assembly interpreter.  Also, table.move is one of those functions that are really not needed. Written in Lua would be just as fast.  Finally, it's not used anywhere else.

(Btw, shouldn't it be `size = size - count` just a few lines above?)
