### ISSUE TITLE
docs: link in the repo's description is broken

### ISSUE THREAD

**Issue by gszr** [Kong/lua-resty-dns-client#96]
correct is http://kong.github.io/lua-resty-dns-client/topics/README.md.html

**Comment by Tieske** [comment]
just ran into this myself, but I'm not authorized to make those changes...

**Comment by hbagdi** [comment]
> just ran into this myself, but I'm not authorized to make those changes...

Please ask internally in engineering to get the permission resolved. You are the maintainer of this repository so you should have this access. @kinman or @guanlan should be able to help out.

**Comment by guanlan** [comment]
> just ran into this myself, but I'm not authorized to make those changes...

Added you as a maintainer of `lua-resty-dns-client` repo.

**Comment by Tieske** [comment]
fixed
